### ISSUE TITLE
Connect and update new radio

### ISSUE THREAD

**Issue by TYNorris** [frc2423/2024-deep-space#8]
Get the new radio working: https://frc-radio.vivid-hosting.net/

- [x] Wire it
- [x] connect from driver station
- [ ] update the firmware: https://frc-radio.vivid-hosting.net/miscellaneous/upgrading-firmware
- [ ] Configure team settings
- [ ] Connect orange pi
- [ ] Mount it

**Comment by CameronBurke1** [comment]
To connect to the radio configuration site, link is http://10.24.23.1
internet name is kwarqs2423-2423 and password is kwarqs2423
